source $VIMRUNTIME/defaults.vim

set tabstop=4
set softtabstop=4
set shiftwidth=4

set number
set mouse=a

if $TERM == "xterm-256color"
	set ttymouse=sgr
endif

colorscheme molokai

nnoremap <Space> <C-f> <C-g>

set hls
